name: Integracao continua - CI

on:
    push:
        branches:
            - develop
            - master
    
    pull_request:
        branches:
            - develop
            - master    

jobs:
    integracao_continua:
        runs-on: self-hosted

        steps:
            - name: BaixarCodigo
              uses: actions/checkout@v4

            - name: Build Projeto de Teste
              shell: cmd
              working-directory: .\Tests
              run: |
                call "C:\Program Files (x86)\Embarcadero\Studio\37.0\bin\rsvars.bat"
                msbuild EConn2026_Test.dproj /p:Config=Release /t:Build /p:DCC_ExeOutput=%GITHUB_WORKSPACE%\Bin\Test  

            - name: Build Projeto Principal
              shell: cmd
              working-directory: .\Fontes
              run: |
                call "C:\Program Files (x86)\Embarcadero\Studio\37.0\bin\rsvars.bat"
                msbuild EConn2026.dproj /p:Config=Release /t:Build /p:DCC_ExeOutput=%GITHUB_WORKSPACE%\Bin  

            - name: Execute Testes unitarios
              shell: cmd
              run: |
                %GITHUB_WORKSPACE%\Bin\Test\EConn2026_Test.exe